### ISSUE TITLE
card does not show on android app

### ISSUE THREAD

**Issue by alinelena** [dckiller51/lovelace-body-miscale-card#11]
the card works fine on my chrome (linux) but on the android app. I get an unknown card error.

**Comment by dckiller51** [comment]
> the card works fine on my chrome (linux) but on the android app. I get an unknown card error.

I don't have the problem on my adroid
![Uploading Screenshot_2021-08-18-13-23-31-400_io.homeassistant.companion.android.jpg…]()

**Comment by dckiller51** [comment]
Look here
https://community.home-assistant.io/t/error-on-some-cards/254001

**Comment by alinelena** [comment]
I am on android 11 up to date I will need to see more where the issue is.

**Comment by alinelena** [comment]
ok seems to fail on desktop on firefox too

**Comment by alinelena** [comment]
problem solved... it seems the issue was cause by the fact the custom card was a symlink..
