### ISSUE TITLE
Show values to lbs

### ISSUE THREAD

**Issue by benquan** [dckiller51/lovelace-body-miscale-card#13]
I usually use pounds(lbs) but the output is only in kg. Could you give a choice in the lovelace configuration to display lbs?

**Comment by dckiller51** [comment]
> I usually use pounds(lbs) but the output is only in kg. Could you give a choice in the lovelace configuration to display lbs?

You only want the unit of measurement or the conversion ?

**Comment by benquan** [comment]
The conversion! I can do it by creating a bunch of template sensors, but it's not a clean solution.

**Comment by dckiller51** [comment]
> La conversion! Je peux le faire en créant un tas de capteurs modèles, mais ce n'est pas une solution propre.

I found the solution. Question in French the units are never in the plural. Example 50 kilograms = 50 kg and not 50 kgs. For you I must put 50 lb or 50 lbs?

**Comment by dckiller51** [comment]
https://github.com/dckiller51/lovelace-body-miscale-card/releases/tag/v5.6.0

**Comment by benquan** [comment]
> > La conversion! Je peux le faire en créant un tas de capteurs modèles, mais ce n'est pas une solution propre.
> 
> I found the solution. Question in French the units are never in the plural. Example 50 kilograms = 50 kg and not 50 kgs. For you I must put 50 lb or 50 lbs?

lbs always

**Comment by benquan** [comment]
Wow! thanks a million!

**Comment by benquan** [comment]
@dckiller51  One minor detail. when graphing, lbs are graphed against kg baseline:

<img width="416" alt="Screen Shot 2021-09-08 at 9 10 36 PM" src="https://user-images.githubusercontent.com/3030645/132616414-cc3386cb-42f7-49da-9d7c-de63ea12eb18.png">

**Comment by dckiller51** [comment]
> @dckiller51 One minor detail. when graphing, lbs are graphed against kg baseline:
> 
> <img alt="Screen Shot 2021-09-08 at 9 10 36 PM" width="416" src="https://user-images.githubusercontent.com/3030645/132616414-cc3386cb-42f7-49da-9d7c-de63ea12eb18.png">

The values have been changed. Attention these data are related to my score. You have to adapt your data with your mitfit application.

https://github.com/dckiller51/lovelace-body-miscale-card#options
