### ISSUE TITLE
italian translate

### ISSUE THREAD

**Issue by max83cb** [dckiller51/lovelace-body-miscale-card#17]
can you add the italian translate?

**Comment by dckiller51** [comment]
> pouvez-vous ajouter la traduction italienne?

The latest version in Italian. your system must be in the Italian language.

**Comment by max83cb** [comment]
i have system in italian but all the stats are in english

**Comment by max83cb** [comment]
![Screenshot_2021-10-04-21-41-57-949_io homeassistant companion android](https://user-images.githubusercontent.com/63288308/135914239-9b759f98-17a4-451b-9678-0fb3a7b6fa31.jpg)

**Comment by dckiller51** [comment]
> j'ai le système en italien mais toutes les statistiques sont en anglais

try to clear cache ctrl + f5

**Comment by dckiller51** [comment]
![Screenshot_2021-10-04-21-47-55-921_io homeassistant companion android](https://user-images.githubusercontent.com/53062806/135914903-90ba3c1e-3f02-43fa-b607-0551ecc45687.jpg)

**Comment by max83cb** [comment]
> > j'ai le système en italien mais toutes les statistiques sont en anglais
> 
> try to clear cache ctrl + f5

i try but don't work

**Comment by dckiller51** [comment]
on mobile I closed the application and reopened to have all the translations initially I only had 50%

**Comment by max83cb** [comment]
i try on pc and mobile app

**Comment by max83cb** [comment]
ok now work. i change language to english and after i select again italian and the translate work
