### ISSUE TITLE
I don't find your card module on HACS.

### ISSUE THREAD

**Issue by mcanteri** [dckiller51/lovelace-body-miscale-card#18]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**

**Description of problem:**

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by dckiller51** [comment]
Hello, it's custom version.

**Comment by mcanteri** [comment]
> Hello, it's custom version.

What does it means ?

**Comment by mcanteri** [comment]
> > Hello, it's custom version.
> 
> What does it mean? Can you explain it in the Readme so everything is consistent?

I followed the install instruction and I still have an error in the log:

2021-11-03 22:22:49 ERROR (MainThread) [frontend.js.latest.202111030] https://xxxx.duckdns.org/hacsfiles/body-miscale-card/body-miscale-card.js?v=1.0.0:1:1 Uncaught SyntaxError: Unexpected token '<'

**Comment by mcanteri** [comment]
After the last Home Assistant update, the error in the log file is gone and the card is available.

**Comment by mcanteri** [comment]
Still have big issues configuring the card, but at least my weight is visible.
