### ISSUE TITLE
Cannot find this in HACS default

### ISSUE THREAD

**Issue by FPMilan** [dckiller51/lovelace-body-miscale-card#19]
When checking in my HACS integration for Frontend addons, I cannot find this card. Would love to install it though. Manual install seams also not possible as the link to the .js file returns a 404 error.
Thanks for any help in advance

**Comment by dckiller51** [comment]
you are right as a bodymiscale I must validate it with hacs. In the meantime, you should be able to install it using the custom repository.

**Comment by FPMilan** [comment]
I wrapped my head around it and it now works nicely!
Only one thing, maybe someone can help with, the Chevron icon to open the additional metrics does not show, I can click the button though. Any one else with this issue?

13.11.2021 15:27:59 dckiller51 ***@***.***>:

**Comment by dckiller51** [comment]
I must correct this error which appeared following the last update of home assistant. a lot of cards we had a similar problem.
