### ISSUE TITLE
Localization to Czech Language

### ISSUE THREAD

**Issue by xpavli44** [dckiller51/lovelace-body-miscale-card#21]
@dckiller51 I'd like to make a Czech translation of your card, can you pls guide me on how to do it?

**Comment by dckiller51** [comment]
> @dckiller51 I'd like to make a Czech translation of your card, can you pls guide me on how to do it?


Hello, look in the link.  You copy one of the files and replace it with your translation.  then you can copy it to me here I will do the integration.

https://github.com/dckiller51/lovelace-body-miscale-card/tree/main/src/localize/languages

**Comment by xpavli44** [comment]
PR https://github.com/dckiller51/lovelace-body-miscale-card/pull/22

**Comment by dckiller51** [comment]
Update 5.6.8 available
