### ISSUE TITLE
Localise unknown state for weight and impedance

### ISSUE THREAD

**Issue by mpavlikWandera** [dckiller51/lovelace-body-miscale-card#28]
Despite translating all the strings in thew localisation file, wight and impedance are shown as "unknown" instead of "neznamý" in Czech localisation. @dckiller51 did I miss some string? Is a code change required to change the behaviour? 
<img width="549" alt="Screenshot 2022-01-07 at 10 57 44" src="https://user-images.githubusercontent.com/64887086/148528755-414bf0be-0039-4e55-839b-c3f861728b8e.png">

**Comment by dckiller51** [comment]
how can i replicate this for testing ?

**Comment by tispokes** [comment]
@dckiller51 rename the sensors name in the `bodymiscale.yaml` and restart HASS. This will cause this problem (for me so far)

**Comment by dckiller51** [comment]
Update 5.8.1 available
