### ISSUE TITLE
Adding Russian

### ISSUE THREAD

**Issue by BrainFixer** [dckiller51/lovelace-body-miscale-card#29]
Hello, I made a translation of your awesome card to Russian (see an attached ru.json). Can you add Russian to your card? Thank you.

[ru.zip](https://github.com/dckiller51/lovelace-body-miscale-card/files/7863497/ru.zip)

**Comment by dckiller51** [comment]
Hello, I'll take care of it for the weekend.

**Comment by dckiller51** [comment]
Update 5.7.0 available
