### ISSUE TITLE
Link to js-file broken

### ISSUE THREAD

**Issue by tispokes** [dckiller51/lovelace-body-miscale-card#31]
According to the `Installation`-part, the link to https://raw.githubusercontent.com/dckiller51/lovelace-body-miscale-card/master/body-miscale-card.js is broken.

**Comment by tispokes** [comment]
Edit: I think the `dist` is missing.
https://raw.githubusercontent.com/dckiller51/lovelace-body-miscale-card/main/dist/body-miscale-card.js works fine

**Comment by tsrubar** [comment]
There was transition master > main clearly too.

**Comment by dckiller51** [comment]
Thanks for reporting it. It's correct.
