### ISSUE TITLE
How to change language?

### ISSUE THREAD

**Issue by JachinY** [dckiller51/lovelace-body-miscale-card#36]
Hi, thank you for your contribution on miscale lovelace, but I don't know how to config this card to make it shown as Chinese, could you help me

**Comment by dckiller51** [comment]
the language is automatic depending on your system. 
You will find on the link the translated languages.

https://github.com/dckiller51/lovelace-body-miscale-card/tree/main/src/localize/languages

**Comment by JachinY** [comment]
> the language is automatic depending on your system. You will find on the link the translated languages.
> 
> https://github.com/dckiller51/lovelace-body-miscale-card/tree/main/src/localize/languages

Actually, in my iPhone it shows ZH-HANS, but on my pc it didnot work, still shows English

**Comment by dckiller51** [comment]
1) Try to switch your system to English 
2) you go to the page of your card you do "update" (f5)
3) delivery of your system in Chinese
4) you go to the page of your map you are "updated" (f5)

**Comment by JachinY** [comment]
> 1. Try to switch your system to English
> 2. you go to the page of your card you do "update" (f5)
> 3. delivery of your system in Chinese
> 4. you go to the page of your map you are "updated" (f5)

I tried step 1 , I switch to ENGLISH and switch back to Chinese, it did work!
Thank you!

**Comment by dckiller51** [comment]
Great
