### ISSUE TITLE
Age Unavailable years 

### ISSUE THREAD

**Issue by sasukebinbin** [dckiller51/lovelace-body-miscale-card#38]
Very strange thing happened. 

3 Users all show "Age: Unavailable years"

Troubleshoot step:
1. Check entity attributes. 
- Got metabolic_age:xx
2. Reload intergration for user. 
- After reload, this user display all good. But all other user become unavailable including kg, age all attributes. 
So reload User A, User B and C will become unavailable. After that, reload User B, User A and User C will become unavailable.
3. Restart HA
- All age become Unavailable. But Weight and Impedance display correct. 

One more question: 
User C age is 4 years old. When add user via UI, there is no metabolic_age:xx shows under attribute. 
Not sure if there is age limited.

**Comment by WalterDSU** [comment]
same problem, age is unavailable after restart.

**Comment by djbombacz** [comment]
Same problem, age is unavailable after restart.

**Comment by dckiller51** [comment]
Update bodymiscale v3.0.5 available
