### ISSUE TITLE
Always show details

### ISSUE THREAD

**Issue by josvink66** [dckiller51/lovelace-body-miscale-card#41]
Hi,

I was wondering if it is possible to always show the details and remove the button?

Greetings,
Jos

**Comment by a7hybnj2** [comment]
I was just looking into this! I see in the HTML it is a toolbar with chevron icon. I can modify the html to show it but I don't know js at all and don't know how to change the actual card.

**Comment by dckiller51** [comment]
Hello, sorry for my late reply. I will try to take the time to add this option.

**Comment by dckiller51** [comment]
Update available v5.9.3
