### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by Xesquy** [dckiller51/lovelace-body-miscale-card#43]
Good morning again, if you want I can also translate the values given by the scale into Spanish.

**Comment by dckiller51** [comment]
The translation is already there. It doesn't work for you?

https://github.com/dckiller51/lovelace-body-miscale-card/blob/main/src/localize/languages/es.json

**Comment by dckiller51** [comment]
> Et bien non, tout sort en anglais, ce que j'ai traduit me convient

It is based on your system. if it's in spanish put back in english HA. Update the page of the card and then you put back in Spanish and again an update of the page. Normally this should work.

**Comment by Xesquy** [comment]
Ok thanks
