### ISSUE TITLE
404 on icon images

### ISSUE THREAD

**Issue by EndermanAPM** [dckiller51/lovelace-body-miscale-card#44]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
5.9.3

**Last working release (if known):**

**Browser and Operating System:**
HA: Manged Raspberry Pi OS

Client:
Windows 10 64b Pro - Chrome 109.0.5414.120
Also happens with the android app

**Description of problem:**

The card is unable to load it's icons, returning a 404.
Also I was unable to set the background image to a local route, had to link to an external image to get it to work.
Might be helpful to know that I'm using the duckdns addon.

![image](https://user-images.githubusercontent.com/3709362/217865599-99c56475-1e23-4a7c-9345-9cca3813cbe8.png)

**Javascript errors shown in the web inspector (if applicable):**

```
body_type.png:1          GET https://[[myduckdns]]/local/images/bodyscoreIcon/body_type.png 404 (Not Found)
bmi.png:1          GET https://[[myduckdns]]/local/images/bodyscoreIcon/bmi.png 404 (Not Found)
protein.png:1          GET https://[[myduckdns]]/local/images/bodyscoreIcon/protein.png 404 (Not Found)
visceral_fat.png:1          GET https://[[myduckdns]]/local/images/bodyscoreIcon/visceral_fat.png 404 (Not Found)
body_fat.png:1          GET https://[[myduckdns]]/local/images/bodyscoreIcon/body_fat.png 404 (Not Found)
water.png:1          GET https://[[myduckdns]]/local/images/bodyscoreIcon/water.png 404 (Not Found)
muscle_mass.png:1          GET https://[[myduckdns]]/local/images/bodyscoreIcon/muscle_mass.png 404 (Not Found)
ideal.png:1          GET https://[[myduckdns]]/local/images/bodyscoreIcon/ideal.png 404 (Not Found)
basal_metabolism.png:1          GET https://[[myduckdns]]/local/images/bodyscoreIcon/basal_metabolism.png 404 (Not Found)
bone_mass.png:1          GET https://[[myduckdns]]/local/images/bodyscoreIcon/bone_mass.png 404 (Not Found)
metabolic_age.png:1          GET https://[[myduckdns]]/local/images/bodyscoreIcon/metabolic_age.png 404 (Not Found)

```

**Additional information:**

**Comment by dckiller51** [comment]
Hello, did you follow this instruction?

For body score icons, download and add [src/images/bodyscoreIcon/*.png](https://raw.githubusercontent.com/dckiller51/lovelace-body-miscale-card/master/src/images/bodyscoreIcon) to <config>/www/images/bodyscoreIcon/

**Comment by dckiller51** [comment]
@EndermanAPM Is your problem solved?

**Comment by l3zha** [comment]
![Скриншот 12-10-2023 164403](https://github.com/dckiller51/lovelace-body-miscale-card/assets/134725565/ebef3d0d-f71b-4723-86c2-3ea96b43b2f5)

No icon

**Comment by l3zha** [comment]
https://raw.githubusercontent.com/dckiller51/lovelace-body-miscale-card/master/src/images/bodyscoreIcon

404: Not Found

**Comment by EndermanAPM** [comment]
Hi @dckiller51 YES, that fixed it. Thanks
p.s. That link and the one in the README are now broken. (seems that the master branch got changed to main at some point)
