### ISSUE TITLE
Icons do not work on Firefox

### ISSUE THREAD

**Issue by nov1n** [dckiller51/lovelace-body-miscale-card#45]
Icons use `webkit-mask-box-image`, which is a nonstandard property without Firefox support ([source](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-mask-box-image)).

As suggested by this source, would it be possible to use [mask-border](https://developer.mozilla.org/en-US/docs/Web/CSS/mask-border) instead?

Many thanks for all your hard work so far!

**Comment by bcutter** [comment]
Yes. They are in the right place. When theme is set to light, nothing is visible. Now that it switched to dark mode, I can see... that there are no icons.

![grafik](https://github.com/dckiller51/lovelace-body-miscale-card/assets/13799156/a676f14d-7650-4fcd-bf7d-e9ef2c1e7da6)


And, by the way: that's what I see in HA Companion app on iOS:
![grafik](https://github.com/dckiller51/lovelace-body-miscale-card/assets/13799156/614173b1-cf9f-4486-8ca3-9b2d801864ea)

Something's really NOT OKAY with those images 😆

**Comment by dckiller51** [comment]
@nov1n @bcutter Can you confirm that the update fixes your icon problem?

**Comment by nov1n** [comment]
Yes it's fixed now, thanks! Confirmed both on Firefox, and on the Android app.

**Comment by bcutter** [comment]
5.9.5:

✅ Yes for
- Firefox as well as HA Companion app (iOS) in dark mode
![grafik](https://github.com/dckiller51/lovelace-body-miscale-card/assets/13799156/0f255110-a0a4-4e34-a17e-ba8c729f4958)

❌ Still a **no** for
- Firefox as well as HA Companion app (iOS) in light mode
![grafik](https://github.com/dckiller51/lovelace-body-miscale-card/assets/13799156/8194bfd9-e3d0-4dfb-bc1f-e67c517acf58)

**Comment by dckiller51** [comment]
> 5.9.5:
> 
> ✅ Yes for
> 
> * Firefox as well as HA Companion app (iOS) in dark mode
>   ![grafik](https://user-images.githubusercontent.com/13799156/270286727-0f255110-a0a4-4e34-a17e-ba8c729f4958.png)
> 
> ❌ Still a **no** for
> 
> * Firefox as well as HA Companion app (iOS) in light mode
>   ![grafik](https://user-images.githubusercontent.com/13799156/270287989-8194bfd9-e3d0-4dfb-bc1f-e67c517acf58.png)

You must use the light or dark theme switch. The switch forces white for dark and uses the default theme colors in light mode.

**Comment by bcutter** [comment]
Ah, great. Looking good now (iOS, away from Firefox currently but for sure fine too).![image](https://github.com/dckiller51/lovelace-body-miscale-card/assets/13799156/8d21ea45-2dfa-42da-9d7f-4a49e7d7937f)

**Comment by dckiller51** [comment]
Thank you both for your feedback. I'm closing this issue.
