### ISSUE TITLE
open for other integrations?

### ISSUE THREAD

**Issue by ChristophCaina** [dckiller51/lovelace-body-miscale-card#51]
**Is your feature request related to a problem? Please describe.**
probably not.

**Describe the solution you'd like**
I am using the Withings Integration, since I am using a Withings BodyScale at home.
I would love to know if the card would also be open for other integrations that provide similar information... I think, it should be not too hard to allow manual configuration for entities?

**Describe alternatives you've considered**
not sure if there are alternatives...

**Additional context**

**Comment by dckiller51** [comment]
The card is linked to the bodymiscale component. You can declare your weight and impedance entity in the component.
