### ISSUE TITLE
Italian language

### ISSUE THREAD

**Issue by wifi75** [dckiller51/lovelace-body-miscale-card#6]
Hello how I can traslate in italian language?

**Comment by dckiller51** [comment]
Hello,
It is possible can you translate this [https://github.com/dckiller51/lovelace-body-miscale-card/blob/main/translations/en.json](url)
Then I integrate it

**Comment by Altar82** [comment]
Hi @dckiller51 ,i have translate it to italian language.
https://pastebin.com/HPt7xfuz
Tell me of it's ok.
Ty

**Comment by dckiller51** [comment]
> Hi @dckiller51 ,i have translate it to italian language. [pastebin.com/HPt7xfuz](https://pastebin.com/HPt7xfuz) Tell me if it's ok. Ty

Thank you for your contribution. Update available.
